/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppppppp;
import javax.swing.*;
import java.sql.*;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author PUSAKR
 */
public class Existing_acc extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Existing_acc.class.getName());

    /**
     * Creates new form Existing_acc
     */String name;
     public Existing_acc()
     {
      initComponents();
     }
    public Existing_acc(String uname) {
        initComponents();
        this.name=uname;
        b5.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        t2 = new javax.swing.JTextField();
        t6 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        b1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b3 = new javax.swing.JButton();
        b4 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb1 = new javax.swing.JTable();
        b5 = new javax.swing.JButton();
        t7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });
        getContentPane().add(t2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 52, 180, 30));

        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });
        getContentPane().add(t6, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 110, 180, 30));

        jLabel2.setText("Account Number");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(76, 50, 110, 30));

        jLabel6.setText("User Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 100, 30));

        b1.setText("Show  Account Details");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });
        getContentPane().add(b1, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, 160, 30));

        b2.setText("Update Account Details");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });
        getContentPane().add(b2, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 60, 160, 30));

        b3.setText("Delete Account");
        b3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b3ActionPerformed(evt);
            }
        });
        getContentPane().add(b3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 110, 160, 30));

        b4.setText("<--");
        b4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b4ActionPerformed(evt);
            }
        });
        getContentPane().add(b4, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 10, 56, -1));

        tb1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tb1);
        if (tb1.getColumnModel().getColumnCount() > 0) {
            tb1.getColumnModel().getColumn(0).setResizable(false);
            tb1.getColumnModel().getColumn(1).setResizable(false);
            tb1.getColumnModel().getColumn(2).setResizable(false);
            tb1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 970, 190));

        b5.setText("Save Changes");
        b5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b5ActionPerformed(evt);
            }
        });
        getContentPane().add(b5, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 420, 140, 40));

        t7.setText("Transaction Details");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });
        getContentPane().add(t7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 110, 160, 30));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t2ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    private void b4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b4ActionPerformed
        this.dispose();
        new acc_management_staff(name).setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_b4ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        String accNo = t2.getText(); 
    try {
           DefaultTableModel model = new DefaultTableModel(
        new Object[]{"acc_no", "Name", "Father","DOB","PAN","Aadhar","Mobile","Email","Address","City","State","Pin","ATM","Branch"}, 0);
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/kkkk", "root", "pus12345");

        String sql = "SELECT * FROM acc WHERE acc_no=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, accNo);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
            t6.setText(rs.getString("Name"));
        model.addRow(new Object[]{
                rs.getString("acc_no"),
             rs.getString("Name"),
             rs.getString("Father"),
             rs.getString("DOB"),
             rs.getString("PAN"),
             rs.getString("Aadhar"),
             rs.getString("Mobile"),
             rs.getString("Email"),
             rs.getString("Address"),
             rs.getString("City"),
             rs.getString("State"),
             rs.getString("Pin"),
             rs.getString("ATM"),
             rs.getString("Branch")
            });
        tb1.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, " ⚠ Account not found!");
        }

        con.close();
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(this, " ⚠ Connection problemm"+e.getMessage());
    }   
    // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
        String accNo = t2.getText().trim();
        if (accNo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an account number!");
            return;
        }

        try {
             DefaultTableModel model = new DefaultTableModel(
        new Object[]{"acc_no", "Name", "Father","DOB","PAN","Aadhar","Mobile","Email","Address","City","State","Pin","ATM","Branch"}, 0);
            
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/kkkk", "root", "pus12345");

            String sql = "SELECT acc_no, Name, Father, DOB,PAN ,Aadhar,Mobile, Email, Address, City,State,Pin,ATM,Branch FROM acc WHERE acc_no = ?";
            PreparedStatement pst = con.prepareStatement(sql);
            pst.setString(1, accNo);
            ResultSet rs = pst.executeQuery();
            model.setRowCount(0); 

            boolean found = false;
            while (rs.next()) {
                found = true;
                 t6.setText(rs.getString("Name"));
                model.addRow(new Object[]{
                    rs.getString("acc_no"),
             rs.getString("Name"),
             rs.getString("Father"),
             rs.getString("DOB"),
             rs.getString("PAN"),
             rs.getString("Aadhar"),
             rs.getString("Mobile"),
             rs.getString("Email"),
             rs.getString("Address"),
             rs.getString("City"),
             rs.getString("State"),
             rs.getString("Pin"),
             rs.getString("ATM"),
             rs.getString("Branch")
                });
                b5.setVisible(true);
            tb1.setModel(model);
            }

            if (!found) {
                JOptionPane.showMessageDialog(this, " ⚠ No account found with this number!");
            }

            con.close();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Error: " + ex.getMessage());
        }// TODO add your handling code here:
    }//GEN-LAST:event_b2ActionPerformed

    private void b3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b3ActionPerformed
try {
    Connection con = DriverManager.getConnection(
        "jdbc:mysql://localhost:3306/kkkk", "root", "pus12345");

    String sql = "DELETE FROM acc WHERE acc_no=?";
    PreparedStatement pst = con.prepareStatement(sql);
    pst.setString(1, t2.getText()); 

    int deleted = pst.executeUpdate();
    if (deleted > 0) {
        JOptionPane.showMessageDialog(this, " ✅ Account Deleted Successfully!");      
        t2.setText("");
        t6.setText("");
    } else {
        JOptionPane.showMessageDialog(this, " ⚠ Account not found!");
    }

    con.close();
} catch (Exception e) {
    e.printStackTrace();
}
        // TODO add your handling code here:
    }//GEN-LAST:event_b3ActionPerformed

    private void b5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b5ActionPerformed
try{
  int selectedRow = tb1.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Please select a row to save changes!");
            return;
        }
         String acc_no = tb1.getValueAt(selectedRow, 0).toString();
        String name = tb1.getValueAt(selectedRow, 1).toString();
        String father = tb1.getValueAt(selectedRow, 2).toString();
        String dob = tb1.getValueAt(selectedRow, 3).toString();
        String pan = tb1.getValueAt(selectedRow, 4).toString();
        String aadhar = tb1.getValueAt(selectedRow, 5).toString();
        String mobile = tb1.getValueAt(selectedRow, 6).toString();
        String email = tb1.getValueAt(selectedRow, 7).toString();
        String address = tb1.getValueAt(selectedRow, 8).toString();
        String city = tb1.getValueAt(selectedRow, 9).toString();
        String state = tb1.getValueAt(selectedRow, 10).toString();
        String pin = tb1.getValueAt(selectedRow, 11).toString();
        String atm = tb1.getValueAt(selectedRow, 12).toString();
        String branch = tb1.getValueAt(selectedRow, 13).toString();
         Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/kkkk", "root", "pus12345");
       
        String sql = "UPDATE acc SET Name=?, Father=?, DOB=?,PAN=?, Aadhar=?, Mobile=?, Email=?, Address=?, City=?, State=?, Pin=?, ATM=?, Branch=? WHERE acc_no=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, name);
        pst.setString(2, father);
        pst.setString(3, dob);
        pst.setString(4, pan);
        pst.setString(5, aadhar);
        pst.setString(6, mobile);
        pst.setString(7, email);
        pst.setString(8, address);
        pst.setString(9, city);
        pst.setString(10, state);
        pst.setString(11, pin);
        pst.setString(12, atm);
        pst.setString(13, branch);
        pst.setString(14, acc_no);
         int updated = pst.executeUpdate();
        if (updated > 0) {
            JOptionPane.showMessageDialog(this, "✅ Account details updated successfully!");
        } else {
            JOptionPane.showMessageDialog(this, "⚠️ No changes made or account not found!");
        }

        con.close();
}
catch(Exception e)
{
     JOptionPane.showMessageDialog(this, "❌ Error updating data: " + e.getMessage());
        e.printStackTrace();
}// TODO add your handling code here:
    }//GEN-LAST:event_b5ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        String acc=t2.getText();
        String name=t6.getText();
                String accNo = t2.getText(); // Account Number field
    
    try {
           DefaultTableModel model = new DefaultTableModel(
        new Object[]{"ID", "SENDER", "RECEIVER","AMOUNT","MESSAGE","Date & Time"}, 0);
        Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/kkkk", "root", "pus12345");

        String sql = "SELECT * FROM transaction WHERE sender=?";
        PreparedStatement pst = con.prepareStatement(sql);
        pst.setString(1, acc);

        ResultSet rs = pst.executeQuery();
        if (rs.next()) {
        model.addRow(new Object[]{
             rs.getString("ID"),
             rs.getString("sender"),
             rs.getString("Receiver"),
             rs.getString("amount"),
             rs.getString("message"),
             rs.getString("trans_date"),
            });
        tb1.setModel(model);
        } else {
            JOptionPane.showMessageDialog(this, " ⚠ Account not found!");
        }

        con.close();
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(this, " ⚠ Connection problemm"+e.getMessage());
    }   

     
        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Existing_acc().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton b3;
    private javax.swing.JButton b4;
    private javax.swing.JButton b5;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t6;
    private javax.swing.JButton t7;
    private javax.swing.JTable tb1;
    // End of variables declaration//GEN-END:variables
}
