/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppppppp;
import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import java.awt.Color;
import java.awt.Font;



import javax.swing.JOptionPane;

/**
 *
 * @author PUSAKR
 */
public class Forget extends javax.swing.JFrame {
    public static String generatedOtp;   
    public static String userEmail;    
    private String currentOtp;
    private int timeLeft = 60; 
    private javax.swing.Timer countdownTimer;

    
 
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Forget.class.getName());
String userRole;
    /**
     * Creates new form Forget
     */
   
       public Forget(String user) {
        initComponents();
        this.userRole = user;
        System.out.println("Selected Role: " + userRole); 
       }
    public Forget() {
        initComponents();
    }
    // Timer countdown for OTP validity



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField1 = new javax.swing.JTextField();
        t5 = new javax.swing.JFormattedTextField();
        t6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextField1.setText("Enter the registered Email ");

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        t6.setText("Send OTP");
        t6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(191, 191, 191)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addComponent(t6, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
     // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void t6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t6ActionPerformed
        String email = t5.getText().trim();
    if (email.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Please enter your registered email.");
        return;
    }

    String table;
    if (userRole.equals("Admin")) table = "dataa";
    else if (userRole.equals("Staff")) table = "staff";
    else table = "user";

    try (Connection con = DriverManager.getConnection(
    "jdbc:mysql://localhost:3306/kkkk?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC",
    "root",
    "pus12345"
);

         PreparedStatement pst = con.prepareStatement("SELECT * FROM " + table + " WHERE email=?")) {
        
        pst.setString(1, email);
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            String otp = String.valueOf(new java.util.Random().nextInt(900000) + 100000);
            generatedOtp = otp;
            userEmail = email;

            // Send OTP Email
            Mail.sendEmail(email, "Password Reset OTP", 
                "Dear User,\n\nYour One-Time Password (OTP) is: " + otp + 
                "\n\nPlease enter this in the OTP verification screen to reset your password.\nThis OTP will expire in 60 seconds.\n\nBest regards,\nSORA Banking System");

            JOptionPane.showMessageDialog(this, "OTP sent to your email successfully!");
            new otp().setVisible(true);
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Email is not registered.");
        }

    } catch (Exception e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(this, "Error sending OTP: " + e.getMessage());
    }
// TODO add your handling code here:
    }//GEN-LAST:event_t6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Forget().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField jTextField1;
    private javax.swing.JFormattedTextField t5;
    private javax.swing.JButton t6;
    // End of variables declaration//GEN-END:variables
}
