/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ppppppp;
import java.awt.Color;
import javax.swing.JOptionPane;
import  javax.swing.*;
import static ppppppp.Forget.generatedOtp;
import java.util.Properties;
import javax.mail.*;
import javax.mail.internet.*;
import java.awt.Color;
import java.awt.Font;


/**
 *
 * @author PUSAKR
 */
public class otp extends javax.swing.JFrame {  
              private String currentOtp;
    private int timeLeft = 60; 
    private javax.swing.Timer countdownTimer;
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(otp.class.getName());

    /**
     * Creates new form otp
     */
    public otp() {
        initComponents();
        startTimer();
    }
private void startTimer() {
    if (countdownTimer != null && countdownTimer.isRunning()) {
        countdownTimer.stop();
    }
    timeLeft = 60;
    t7.setEnabled(false); // disable resend button
     m2.setForeground(Color.BLUE);
     m2.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 14));
    countdownTimer = new javax.swing.Timer(1000, new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent e) {
            timeLeft--;
            m2.setText("OTP valid for " + timeLeft + "s");

            if (timeLeft <= 0) {
                countdownTimer.stop();
                m2.setText("OTP expired! Please resend.");
                generatedOtp = null; // invalidate OTP
                t7.setEnabled(true); // allow resend
            }
        }
    });
    countdownTimer.start();
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        b1 = new javax.swing.JButton();
        t5 = new javax.swing.JFormattedTextField();
        m2 = new javax.swing.JLabel();
        t7 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        b1.setText("Verify");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        t5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t5ActionPerformed(evt);
            }
        });

        t7.setText("Resend OTP");
        t7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t7ActionPerformed(evt);
            }
        });

        jLabel2.setText("Enter OTP :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(66, 66, 66))
            .addGroup(layout.createSequentialGroup()
                .addGap(188, 188, 188)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addComponent(m2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(b1)
                .addGap(37, 37, 37)
                .addComponent(t7, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void t5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t5ActionPerformed
      // TODO add your handling code here:
    }//GEN-LAST:event_t5ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
       if (t5.getText().trim().equals(Forget.generatedOtp)) {
    JOptionPane.showMessageDialog(this," OTP verified ✅❤️‍? !!!");
    new Resett().setVisible(true);
    this.dispose();
} else {
    JOptionPane.showMessageDialog(this," ⚠ Wrong OTP !!!");
}

        // TODO add your handling code here:
    }//GEN-LAST:event_b1ActionPerformed

    private void t7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t7ActionPerformed
        if (Forget.userEmail == null || Forget.userEmail.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter your registered email first!");
            return;
        }

        try {
            String otp = String.valueOf(new java.util.Random().nextInt(900000) + 100000);
            generatedOtp = otp;

            Mail.sendEmail(Forget.userEmail, "Password Reset OTP (Resent)",
                "Dear User,\n\nYour new OTP is: " + otp +
                "\n\nnPlease enter this in the OTP verification screen to reset your password.\nThis OTP will expire in 60 seconds.\n\nBest regards,\nSORA Banking System");

            JOptionPane.showMessageDialog(this, "New OTP sent to your email!");
            startTimer(); // restart countdown
            t7.setEnabled(false); // disable resend until next expiry
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error resending OTP: " + e.getMessage());
        }        // TODO add your handling code here:
    }//GEN-LAST:event_t7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new otp().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton b1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel m2;
    private javax.swing.JFormattedTextField t5;
    private javax.swing.JButton t7;
    // End of variables declaration//GEN-END:variables
}
